server:
  port: 8080
  servlet:
    context-path: /note
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/note?characterEncoding=utf8&allowMultiQueries=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      #配置初始化大小/最小/最大
      initial-size: 1
      min-idle: 1
      max-active: 20
      #获取连接等待超时时间
      max-wait: 60000
  mail:
    host: smtp.163.com   #邮箱服务器地址
    username: hi_itao@163.com   #邮箱账号
    password: DUKLCSBQGPFITHQT  #邮箱授权码
    default-encoding: utf-8    #默认编码
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 1
      #    password: 123456 #默认为空
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 20  # 最大连接数，负值表示没有限制，默认8
          max-wait: -1    # 最大阻塞等待时间，负值表示没限制，默认-1
          max-idle: 8     # 最大空闲连接，默认8
          min-idle: 0     # 最小空闲连接，默认0
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
mybatis-plus:
  # MyBatis映射器文件的位置
  mapper-locations: classpath*:mapper/*Mapper.xml
  global-config:
    db-config:
      logic-delete-field: isDelete #默认deleted
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
      table-underline: true # 实体类属性名和数据库表字段名是否开启驼峰命名法
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# 日志文件的保存目录设置
logging:
  config: classpath:log-config.xml
#邮件发件人
mail:
  fromMail:
    fromAddress: hi_itao@163.com
#对登录密码二次加盐
md5encrypt:
  addSalt:
    value: one_ao
# minio配置
minio:
  endpoint: http://127.0.0.1:9000
  accessKey: minioadmin
  secretKey: minioadmin
  bucketName: note-bucket
# 前端分享地址
front:
  share:
    address: http://localhost:5173/noteShare
chatgpt:
  token: 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 #必填
  proxy-host: 127.0.0.1 #需要代理时必填
  proxy-port: 7890 #需要代理时必填
  # model: text-davinci-003 #可选
  chat-model: gpt-3.5-turbo #可选
  retries: 3 #可选，默认为5
  session-expiration-time: 5 #可选，不填则会话永不过期
#  base-url: https://apps.ichati.cn/1d6f32f8-b59d-46f8-85e9-7d434bxxxxxx/ #可选，默认为https://api.openai.com/，请记住务必以/结尾

